/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bioquest.bioquest_pi.telas;

import com.bioquest.bioquest_pi.bd.QuestoesCAD;
import com.bioquest.bioquest_pi.bd.UsuarioCAD;
import com.bioquest.bioquest_pi.modelo.Questoes;
import com.bioquest.bioquest_pi.modelo.Sala;
import com.bioquest.bioquest_pi.modelo.Usuario;
import java.awt.Color;

/**
 *
 * @author Thamires aa
 */
public class CriarQuizTela extends javax.swing.JFrame {

    /**
     * Creates new form CriarQuizTela
     */
    public CriarQuizTela() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPerguntaButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        nomeQuizTextField = new javax.swing.JTextField();
        materiaTextField = new javax.swing.JTextField();
        perguntaTextField = new javax.swing.JTextField();
        altATextField = new javax.swing.JTextField();
        altBTextField = new javax.swing.JTextField();
        altCTextField = new javax.swing.JTextField();
        altDTextField = new javax.swing.JTextField();
        numQuestaoTextField = new javax.swing.JTextField();
        altCorretaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        idQuizTextField = new javax.swing.JTextField();
        idSalaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addPerguntaButton.setBackground(new java.awt.Color(131, 177, 0));
        addPerguntaButton.setText("adicionar pergunta");
        addPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPerguntaButtonActionPerformed(evt);
            }
        });

        voltarButton.setBackground(new java.awt.Color(255, 98, 49));
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        nomeQuizTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do Quiz:"));
        nomeQuizTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeQuizTextFieldActionPerformed(evt);
            }
        });

        materiaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Matéria:"));

        perguntaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicione o Texto da Pergunta:"));

        altATextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicione o Texto da alternativa A:"));

        altBTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicione o Texto da Alternativa B:"));

        altCTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicione o Texto da Alternativa C:"));

        altDTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Texto da Alternativa D:"));

        numQuestaoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Número da Questão:"));

        altCorretaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Alternativa Correta:"));

        jTextPane1.setEditable(false);
        jTextPane1.setText("Apenas qual alternativa (ex: A)");
        jScrollPane1.setViewportView(jTextPane1);
        jTextPane1.getAccessibleContext().setAccessibleName("");

        idQuizTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("ID do Quiz:"));

        idSalaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("ID da Sala:"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(addPerguntaButton)
                        .addGap(74, 74, 74)
                        .addComponent(voltarButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nomeQuizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(materiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(perguntaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numQuestaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(altCorretaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idQuizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idSalaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeQuizTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(materiaTextField)
                    .addComponent(idQuizTextField)
                    .addComponent(idSalaTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(perguntaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numQuestaoTextField)
                            .addComponent(altCorretaTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(altATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPerguntaButton)
                    .addComponent(voltarButton))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        TelaProfessor telap = new TelaProfessor();
        this.dispose();
        telap.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void nomeQuizTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeQuizTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeQuizTextFieldActionPerformed

    private void addPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPerguntaButtonActionPerformed
        Questoes q = new Questoes();
        q.setIdquestoes(Integer.parseInt(numQuestaoTextField.getText()));
        q.setPergunta(perguntaTextField.getText());
        q.setAlt_a(altATextField.getText());
        q.setAlt_b(altBTextField.getText());
        q.setAlt_c(altCTextField.getText());
        q.setAlt_d(altDTextField.getText());
        q.setAlt_correta(altCorretaTextField.getText());
        q.setIdquiz(Integer.parseInt(idQuizTextField.getText()));
        QuestoesCAD cad = new QuestoesCAD();
        cad.inserir(q);
        LoginTela loginTela = new LoginTela();
        this.dispose();
        loginTela.setVisible(true);
    }//GEN-LAST:event_addPerguntaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarQuizTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarQuizTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarQuizTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarQuizTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarQuizTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPerguntaButton;
    private javax.swing.JTextField altATextField;
    private javax.swing.JTextField altBTextField;
    private javax.swing.JTextField altCTextField;
    private javax.swing.JTextField altCorretaTextField;
    private javax.swing.JTextField altDTextField;
    private javax.swing.JTextField idQuizTextField;
    private javax.swing.JTextField idSalaTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField materiaTextField;
    private javax.swing.JTextField nomeQuizTextField;
    private javax.swing.JTextField numQuestaoTextField;
    private javax.swing.JTextField perguntaTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
